name: envio-indexer
contracts:
  - name: MockPYUSD
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: ProtocolContract
    handler: src/EventHandlers.ts
    events:
      - event: DisputeCreated(uint256 indexed disputeId, address indexed requester, address indexed contractAddress)
      - event: DisputeResolved(uint256 indexed disputeId, address winner)
      - event: JudgeRegistered(address indexed judge)
  - name: FactoryContract
    handler: src/EventHandlers.ts
    events:
      - event: MarketplaceDeployed(address indexed marketplace, address indexed creator)
networks:
  - id: 31337
    start_block: 1
    rpc_config:
      url: http://localhost:8545
    contracts:
      - name: MockPYUSD
        address:
          - '0x700b6a60ce7eaaea56f065753d8dcb9653dbad35'
      - name: ProtocolContract
        address:
          - '0xa15bb66138824a1c7167f5e85b957d04dd34e468'
      - name: FactoryContract
        address:
          - '0xb19b36b1456e65e3a6d514d3f715f204bd59f431'
unordered_multichain_mode: true
preload_handlers: true
